# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dab869a639cc90211b86d1dbdf00584ac7cf32e8e026bf2dad5f8cda252d69e36c0d49408865c307a4140a6e64f8a813b4b21f5c52322f160fa15207822a7de

test:
  secret_key_base: 2fd9926cd3b504995306489fc8d294271dca95dd11e64f0f6c4e856903791285ca47abbadc8d292cd11dcd05174cb904fb8779704e36da77d3ac03372ffb4807

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
